male(Авдей).
male(Авксентий).
female(Аврора).
male(Авдей).
male(Авксентий).
female(Аврора).
male(Авдей).
male(Авксентий).
female(Аврора).
male(Авдей).
male(Авксентий).
female(Аврора).
male(Авдей).
male(Авксентий).
female(Аврора).
male(Авдей).
male(Авксентий).
female(Аврора).
male(Авдей).
male(Авксентий).
female(Аврора).
male(Авдей).
male(Авксентий).
female(Аврора).
male(Авдей).
male(Авксентий).
female(Аврора).
male(Авдей).
male(Авксентий).
female(Аврора).
male(Авдей).
male(Авдей).
male(Авксентий).
female(Аврора).
male(Авдей).
male(Авксентий).
female(Аврора).
male(Авдей).
male(Авксентий).
female(Аврора).
male(Авдей).
male(Авксентий).
female(Аврора).
male(Авдей).
male(Авксентий).
female(Аврора).
male(Авдей).
male(Авксентий).
female(Аврора).
male(Авдей).
male(Авксентий).
female(Аврора).
male(Авдей).
male(Авксентий).
female(Аврора).
male(Авдей).
male(Авксентий).
female(Аврора).
male(Авдей).
male(Авксентий).
female(Аврора).
male(Авдей).
male(Авксентий).
female(Аврора).
male(Авдей).
male(Авксентий).
female(Аврора).
male(Авдей).
male(Авксентий).
female(Аврора).
